import type { Pole, User } from "./types";

export const mockPoles: Pole[] = [
  {
    id: "pole-00931",
    assetTag: "CPL-A-00931",
    customerId: "cust-001",
    customerName: "Coastal Power & Light",
    projectId: "proj-101",
    projectName: "Bayou District Rebuild",
    status: "active",
    material: "Wood, Southern Pine",
    heightFt: 40,
    latitude: 29.9511,
    longitude: -90.0715,
    lastInspected: "2026-06-02",
  },
  {
    id: "pole-00932",
    assetTag: "CPL-A-00932",
    customerId: "cust-001",
    customerName: "Coastal Power & Light",
    projectId: "proj-101",
    projectName: "Bayou District Rebuild",
    status: "flagged",
    material: "Wood, Southern Pine",
    heightFt: 40,
    latitude: 29.9518,
    longitude: -90.0702,
    lastInspected: "2026-04-19",
  },
  {
    id: "pole-01204",
    assetTag: "CPL-B-01204",
    customerId: "cust-001",
    customerName: "Coastal Power & Light",
    projectId: "proj-102",
    projectName: "Storm Hardening Phase 2",
    status: "planned",
    material: "Steel",
    heightFt: 45,
    latitude: 30.0687,
    longitude: -89.9308,
    lastInspected: "—",
  },
  {
    id: "pole-05512",
    assetTag: "HTC-N-05512",
    customerId: "cust-002",
    customerName: "Highline Telecom Cooperative",
    projectId: "proj-201",
    projectName: "Fiber Overbuild North",
    status: "active",
    material: "Wood, Douglas Fir",
    heightFt: 35,
    latitude: 44.9778,
    longitude: -93.265,
    lastInspected: "2026-05-27",
  },
  {
    id: "pole-05513",
    assetTag: "HTC-N-05513",
    customerId: "cust-002",
    customerName: "Highline Telecom Cooperative",
    projectId: "proj-201",
    projectName: "Fiber Overbuild North",
    status: "active",
    material: "Wood, Douglas Fir",
    heightFt: 35,
    latitude: 44.9791,
    longitude: -93.2634,
    lastInspected: "2026-05-27",
  },
  {
    id: "pole-07781",
    assetTag: "SRE-R-07781",
    customerId: "cust-003",
    customerName: "Summit Rural Electric",
    projectId: "proj-301",
    projectName: "Ridge Line Replacement",
    status: "decommissioned",
    material: "Concrete",
    heightFt: 50,
    latitude: 39.7392,
    longitude: -104.9903,
    lastInspected: "2026-01-11",
  },
  {
    id: "pole-09901",
    assetTag: "BMU-H-09901",
    customerId: "cust-004",
    customerName: "Bayfront Municipal Utilities",
    projectId: "proj-401",
    projectName: "Harbor Rd Undergrounding",
    status: "flagged",
    material: "Wood, Southern Pine",
    heightFt: 40,
    latitude: 41.4901,
    longitude: -71.3128,
    lastInspected: "2026-03-08",
  },
  {
    id: "pole-11245",
    assetTag: "PFP-L-11245",
    customerId: "cust-005",
    customerName: "Piedmont Fiber Partners",
    projectId: "proj-501",
    projectName: "Piedmont Loop Expansion",
    status: "active",
    material: "Steel",
    heightFt: 38,
    latitude: 35.7796,
    longitude: -78.6382,
    lastInspected: "2026-07-01",
  },
];

export const mockUsers: User[] = [
  {
    id: "user-01",
    name: "Dana Whitfield",
    email: "dana.whitfield@internal.co",
    role: "admin",
    active: true,
    lastActive: "2026-07-21",
  },
  {
    id: "user-02",
    name: "Marcus Ellery",
    email: "marcus.ellery@internal.co",
    role: "editor",
    active: true,
    lastActive: "2026-07-20",
  },
  {
    id: "user-03",
    name: "Priya Nandakumar",
    email: "priya.nandakumar@internal.co",
    role: "editor",
    active: true,
    lastActive: "2026-07-18",
  },
  {
    id: "user-04",
    name: "Colin Ashworth",
    email: "colin.ashworth@internal.co",
    role: "viewer",
    active: false,
    lastActive: "2026-05-30",
  },
];
