import type { Customer, Pole, Project, User } from "./types";

export const mockCustomers: Customer[] = [
  {
    id: "cust-001",
    name: "Coastal Power & Light",
    accountCode: "CPL-2291",
    region: "Gulf Coast",
    status: "active",
    projectCount: 4,
    poleCount: 812,
    updatedAt: "2026-07-14",
  },
  {
    id: "cust-002",
    name: "Highline Telecom Cooperative",
    accountCode: "HTC-0087",
    region: "Midwest",
    status: "active",
    projectCount: 2,
    poleCount: 431,
    updatedAt: "2026-07-10",
  },
  {
    id: "cust-003",
    name: "Summit Rural Electric",
    accountCode: "SRE-1140",
    region: "Mountain West",
    status: "active",
    projectCount: 3,
    poleCount: 296,
    updatedAt: "2026-06-29",
  },
  {
    id: "cust-004",
    name: "Bayfront Municipal Utilities",
    accountCode: "BMU-0552",
    region: "Northeast",
    status: "inactive",
    projectCount: 1,
    poleCount: 58,
    updatedAt: "2026-05-02",
  },
  {
    id: "cust-005",
    name: "Piedmont Fiber Partners",
    accountCode: "PFP-3305",
    region: "Southeast",
    status: "active",
    projectCount: 2,
    poleCount: 174,
    updatedAt: "2026-07-18",
  },
];

export const mockProjects: Project[] = [
  { id: "proj-101", customerId: "cust-001", name: "Bayou District Rebuild", code: "CPL-24-A", poleCount: 340 },
  { id: "proj-102", customerId: "cust-001", name: "Storm Hardening Phase 2", code: "CPL-24-B", poleCount: 472 },
  { id: "proj-201", customerId: "cust-002", name: "Fiber Overbuild North", code: "HTC-23-N", poleCount: 431 },
  { id: "proj-301", customerId: "cust-003", name: "Ridge Line Replacement", code: "SRE-25-R", poleCount: 296 },
  { id: "proj-401", customerId: "cust-004", name: "Harbor Rd Undergrounding", code: "BMU-22-H", poleCount: 58 },
  { id: "proj-501", customerId: "cust-005", name: "Piedmont Loop Expansion", code: "PFP-24-L", poleCount: 174 },
];

export const mockPoles: Pole[] = [
  {
    id: "pole-00931",
    assetTag: "CPL-A-00931",
    customerId: "cust-001",
    customerName: "Coastal Power & Light",
    projectId: "proj-101",
    projectName: "Bayou District Rebuild",
    status: "active",
    material: "Wood, Southern Pine",
    heightFt: 40,
    latitude: 29.9511,
    longitude: -90.0715,
    lastInspected: "2026-06-02",
  },
  {
    id: "pole-00932",
    assetTag: "CPL-A-00932",
    customerId: "cust-001",
    customerName: "Coastal Power & Light",
    projectId: "proj-101",
    projectName: "Bayou District Rebuild",
    status: "flagged",
    material: "Wood, Southern Pine",
    heightFt: 40,
    latitude: 29.9518,
    longitude: -90.0702,
    lastInspected: "2026-04-19",
  },
  {
    id: "pole-01204",
    assetTag: "CPL-B-01204",
    customerId: "cust-001",
    customerName: "Coastal Power & Light",
    projectId: "proj-102",
    projectName: "Storm Hardening Phase 2",
    status: "planned",
    material: "Steel",
    heightFt: 45,
    latitude: 30.0687,
    longitude: -89.9308,
    lastInspected: "—",
  },
  {
    id: "pole-05512",
    assetTag: "HTC-N-05512",
    customerId: "cust-002",
    customerName: "Highline Telecom Cooperative",
    projectId: "proj-201",
    projectName: "Fiber Overbuild North",
    status: "active",
    material: "Wood, Douglas Fir",
    heightFt: 35,
    latitude: 44.9778,
    longitude: -93.265,
    lastInspected: "2026-05-27",
  },
  {
    id: "pole-05513",
    assetTag: "HTC-N-05513",
    customerId: "cust-002",
    customerName: "Highline Telecom Cooperative",
    projectId: "proj-201",
    projectName: "Fiber Overbuild North",
    status: "active",
    material: "Wood, Douglas Fir",
    heightFt: 35,
    latitude: 44.9791,
    longitude: -93.2634,
    lastInspected: "2026-05-27",
  },
  {
    id: "pole-07781",
    assetTag: "SRE-R-07781",
    customerId: "cust-003",
    customerName: "Summit Rural Electric",
    projectId: "proj-301",
    projectName: "Ridge Line Replacement",
    status: "decommissioned",
    material: "Concrete",
    heightFt: 50,
    latitude: 39.7392,
    longitude: -104.9903,
    lastInspected: "2026-01-11",
  },
  {
    id: "pole-09901",
    assetTag: "BMU-H-09901",
    customerId: "cust-004",
    customerName: "Bayfront Municipal Utilities",
    projectId: "proj-401",
    projectName: "Harbor Rd Undergrounding",
    status: "flagged",
    material: "Wood, Southern Pine",
    heightFt: 40,
    latitude: 41.4901,
    longitude: -71.3128,
    lastInspected: "2026-03-08",
  },
  {
    id: "pole-11245",
    assetTag: "PFP-L-11245",
    customerId: "cust-005",
    customerName: "Piedmont Fiber Partners",
    projectId: "proj-501",
    projectName: "Piedmont Loop Expansion",
    status: "active",
    material: "Steel",
    heightFt: 38,
    latitude: 35.7796,
    longitude: -78.6382,
    lastInspected: "2026-07-01",
  },
];

export const mockUsers: User[] = [
  {
    id: "user-01",
    name: "Dana Whitfield",
    email: "dana.whitfield@internal.co",
    role: "admin",
    active: true,
    lastActive: "2026-07-21",
  },
  {
    id: "user-02",
    name: "Marcus Ellery",
    email: "marcus.ellery@internal.co",
    role: "editor",
    active: true,
    lastActive: "2026-07-20",
  },
  {
    id: "user-03",
    name: "Priya Nandakumar",
    email: "priya.nandakumar@internal.co",
    role: "editor",
    active: true,
    lastActive: "2026-07-18",
  },
  {
    id: "user-04",
    name: "Colin Ashworth",
    email: "colin.ashworth@internal.co",
    role: "viewer",
    active: false,
    lastActive: "2026-05-30",
  },
];
